# Generated by Django 2.1.7 on 2019-08-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0002_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.TextField(),
        ),
    ]
