# Generated by Django 2.1.7 on 2019-09-09 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0004_auto_20190825_0832'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
