# Generated by Django 2.1.7 on 2019-09-09 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0006_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
