# Generated by Django 2.1.7 on 2019-09-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stockapp', '0007_auto_20190909_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
